name: 'deploy website and ebooks'

on:
  push:
    branches:
      - master

jobs:
  job_deploy_website:
    name: 'deploy website'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: 'Installing gitbook cli'
      run: npm install -g gitbook-cli
    - name: 'Generating distributable files'
      run: |
        mv book.json.template book.json
        gitbook install
        gitbook build
        go run adjustment.go
        cd _book
        echo '<html><head><meta http-equiv="refresh" content="0; url=https://dasarpemrogramangolang.novalagung.com/"></head></html>' > 404.html
        rm -rf LICENSE
        rm -rf book*
        rm -rf .git
        rm -rf .gitignore
        rm -rf .github
        rm -rf *.md
        rm -rf *.go
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book

  job_deploy_ebook:
    name: 'deploy ebook'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 11
        check-latest: true
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: 'Installing requirements'
      run: |
        npm install -g gitbook-cli svgexport
        sudo apt install libegl1 libopengl0
        sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
    - name: 'Generating distributable files'
      run: |
        gitbook install
        gitbook build
        go run adjustment.go
        cd _book
        gitbook install
    - name: 'Generating ebook in pdf'
      run: gitbook pdf ./ ./_book/learndevops.pdf
    - name: 'Generating ebook in epub'
      run: gitbook epub ./ ./_book/learndevops.epub
    - name: 'Generating ebook in mobi'
      run: gitbook mobi ./ ./_book/learndevops.mobi
    - name: 'Deploying'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book
        publish_branch: ebooks
